### ISSUE TITLE
Create Documentation how to use app (how to test)

### ISSUE THREAD

**Issue by jufianto** [vck/another-url-shortener#2]
for better test and use, I think you should make docs how to use your app. 
so I can test and try your code and if i edit your app so i can make sure your app is not crash or error

**Comment by vck** [comment]
@jufianto docs updated on https://github.com/vck/another-url-shortener/commit/221d1976f4580ca89b1e7058c4982759928d685e
feel free to close the issue if the above commit suffiece what you need :smiley:

**Comment by vck** [comment]
closing the issue as docs already added
